import type { Bus } from '../types';

export const mockBuses: Bus[] = [
  {
    id: 1,
    name: 'Samay Express',
    from: 'Delhi',
    to: 'Agra',
    departureTime: '06:00 AM',
    arrivalTime: '10:30 AM',
    duration: '4h 30m',
    price: 450,
    seatsLeft: 3,
    rating: 4.2,
    reviews: 1200,
    amenities: ['AC', 'WiFi', 'USB Charging'],
    busType: 'AC Seater',
  },
  {
    id: 2,
    name: 'Royal Travels',
    from: 'Delhi',
    to: 'Agra',
    departureTime: '08:00 AM',
    arrivalTime: '12:00 PM',
    duration: '4h',
    price: 550,
    seatsLeft: 8,
    rating: 4.5,
    reviews: 2300,
    amenities: ['AC', 'WiFi', 'USB Charging', 'Water Bottle'],
    busType: 'AC Seater',
  },
  {
    id: 3,
    name: 'Night Express',
    from: 'Delhi',
    to: 'Agra',
    departureTime: '10:00 PM',
    arrivalTime: '03:30 AM',
    duration: '5h 30m',
    price: 650,
    seatsLeft: 12,
    rating: 4.3,
    reviews: 980,
    amenities: ['AC', 'WiFi', 'USB Charging', 'Blanket', 'Water Bottle'],
    busType: 'AC Sleeper',
  },
  {
    id: 4,
    name: 'Speed Line',
    from: 'Delhi',
    to: 'Agra',
    departureTime: '12:00 PM',
    arrivalTime: '04:15 PM',
    duration: '4h 15m',
    price: 420,
    seatsLeft: 5,
    rating: 4.0,
    reviews: 750,
    amenities: ['AC', 'USB Charging'],
    busType: 'AC Seater',
  },
  {
    id: 5,
    name: 'Comfort Plus',
    from: 'Delhi',
    to: 'Agra',
    departureTime: '02:00 PM',
    arrivalTime: '06:45 PM',
    duration: '4h 45m',
    price: 580,
    seatsLeft: 15,
    rating: 4.6,
    reviews: 3200,
    amenities: ['AC', 'WiFi', 'USB Charging', 'Water Bottle', 'Snacks'],
    busType: 'AC Seater',
  },
  {
    id: 6,
    name: 'Budget Travels',
    from: 'Delhi',
    to: 'Agra',
    departureTime: '07:00 AM',
    arrivalTime: '12:00 PM',
    duration: '5h',
    price: 280,
    seatsLeft: 20,
    rating: 3.8,
    reviews: 450,
    amenities: ['Fan', 'Water Bottle'],
    busType: 'Non-AC Seater',
  },
  {
    id: 7,
    name: 'Luxury Coach',
    from: 'Delhi',
    to: 'Agra',
    departureTime: '09:00 AM',
    arrivalTime: '01:00 PM',
    duration: '4h',
    price: 750,
    seatsLeft: 6,
    rating: 4.8,
    reviews: 4100,
    amenities: ['AC', 'WiFi', 'USB Charging', 'Water Bottle', 'Snacks', 'Reading Light'],
    busType: 'Volvo Multi-Axle',
  },
  {
    id: 8,
    name: 'Morning Star',
    from: 'Delhi',
    to: 'Agra',
    departureTime: '05:30 AM',
    arrivalTime: '10:00 AM',
    duration: '4h 30m',
    price: 480,
    seatsLeft: 10,
    rating: 4.4,
    reviews: 1580,
    amenities: ['AC', 'WiFi', 'USB Charging', 'Water Bottle'],
    busType: 'AC Seater',
  },
  {
    id: 9,
    name: 'Blue Bird Travels',
    from: 'Delhi',
    to: 'Agra',
    departureTime: '06:30 AM',
    arrivalTime: '11:15 AM',
    duration: '4h 45m',
    price: 520,
    seatsLeft: 7,
    rating: 4.1,
    reviews: 890,
    amenities: ['AC', 'USB Charging'],
    busType: 'AC Seater',
  },
  {
    id: 10,
    name: 'Eagle Express',
    from: 'Delhi',
    to: 'Agra',
    departureTime: '09:30 AM',
    arrivalTime: '02:00 PM',
    duration: '4h 30m',
    price: 490,
    seatsLeft: 18,
    rating: 4.3,
    reviews: 1250,
    amenities: ['AC', 'WiFi', 'USB Charging'],
    busType: 'AC Seater',
  },
  {
    id: 11,
    name: 'Night Rider',
    from: 'Delhi',
    to: 'Agra',
    departureTime: '11:00 PM',
    arrivalTime: '04:30 AM',
    duration: '5h 30m',
    price: 620,
    seatsLeft: 9,
    rating: 4.4,
    reviews: 2100,
    amenities: ['AC', 'WiFi', 'USB Charging', 'Blanket', 'Water Bottle'],
    busType: 'AC Sleeper',
  },
  {
    id: 12,
    name: 'Super Fast',
    from: 'Delhi',
    to: 'Agra',
    departureTime: '03:00 PM',
    arrivalTime: '07:30 PM',
    duration: '4h 30m',
    price: 460,
    seatsLeft: 14,
    rating: 4.0,
    reviews: 680,
    amenities: ['AC', 'USB Charging', 'Water Bottle'],
    busType: 'AC Seater',
  },
  {
    id: 13,
    name: 'Golden Travels',
    from: 'Delhi',
    to: 'Agra',
    departureTime: '04:00 PM',
    arrivalTime: '08:45 PM',
    duration: '4h 45m',
    price: 540,
    seatsLeft: 11,
    rating: 4.5,
    reviews: 1850,
    amenities: ['AC', 'WiFi', 'USB Charging', 'Water Bottle', 'Snacks'],
    busType: 'AC Seater',
  },
  {
    id: 14,
    name: 'Economy Express',
    from: 'Delhi',
    to: 'Agra',
    departureTime: '08:30 AM',
    arrivalTime: '01:30 PM',
    duration: '5h',
    price: 320,
    seatsLeft: 25,
    rating: 3.7,
    reviews: 560,
    amenities: ['Fan', 'Water Bottle'],
    busType: 'Non-AC Seater',
  },
  {
    id: 15,
    name: 'Royal Sleeper',
    from: 'Delhi',
    to: 'Agra',
    departureTime: '09:30 PM',
    arrivalTime: '02:30 AM',
    duration: '5h',
    price: 700,
    seatsLeft: 4,
    rating: 4.7,
    reviews: 2890,
    amenities: ['AC', 'WiFi', 'USB Charging', 'Blanket', 'Water Bottle', 'Reading Light'],
    busType: 'AC Sleeper',
  },
  {
    id: 16,
    name: 'City Link',
    from: 'Delhi',
    to: 'Agra',
    departureTime: '11:00 AM',
    arrivalTime: '03:30 PM',
    duration: '4h 30m',
    price: 440,
    seatsLeft: 16,
    rating: 4.2,
    reviews: 1340,
    amenities: ['AC', 'USB Charging'],
    busType: 'AC Seater',
  },
  {
    id: 17,
    name: 'Prime Travels',
    from: 'Delhi',
    to: 'Agra',
    departureTime: '01:00 PM',
    arrivalTime: '05:30 PM',
    duration: '4h 30m',
    price: 500,
    seatsLeft: 12,
    rating: 4.4,
    reviews: 1670,
    amenities: ['AC', 'WiFi', 'USB Charging', 'Water Bottle'],
    busType: 'AC Seater',
  },
  {
    id: 18,
    name: 'Volvo Express',
    from: 'Delhi',
    to: 'Agra',
    departureTime: '06:00 AM',
    arrivalTime: '09:45 AM',
    duration: '3h 45m',
    price: 850,
    seatsLeft: 5,
    rating: 4.9,
    reviews: 5200,
    amenities: ['AC', 'WiFi', 'USB Charging', 'Water Bottle', 'Snacks', 'Reading Light', 'Blanket'],
    busType: 'Volvo Multi-Axle',
  },
  {
    id: 19,
    name: 'Day Runner',
    from: 'Delhi',
    to: 'Agra',
    departureTime: '07:30 AM',
    arrivalTime: '12:15 PM',
    duration: '4h 45m',
    price: 395,
    seatsLeft: 19,
    rating: 3.9,
    reviews: 720,
    amenities: ['AC', 'Water Bottle'],
    busType: 'AC Seater',
  },
  {
    id: 20,
    name: 'Midnight Comfort',
    from: 'Delhi',
    to: 'Agra',
    departureTime: '12:00 AM',
    arrivalTime: '05:00 AM',
    duration: '5h',
    price: 680,
    seatsLeft: 8,
    rating: 4.6,
    reviews: 3100,
    amenities: ['AC', 'WiFi', 'USB Charging', 'Blanket', 'Water Bottle', 'Reading Light'],
    busType: 'AC Sleeper',
  },
];

export const mockLocations = [
  'Delhi',
  'Agra',
  'Mumbai',
  'Pune',
  'Bangalore',
  'Hyderabad',
  'Chennai',
  'Kolkata',
  'Jaipur',
  'Lucknow',
  'Chandigarh',
  'Ahmedabad',
];
