import type { Bus } from '../types';

export const mockBuses: Bus[] = [
  {
    id: 1,
    name: 'Samay Express',
    from: 'Delhi',
    to: 'Agra',
    departureTime: '06:00 AM',
    arrivalTime: '10:30 AM',
    duration: '4h 30m',
    price: 450,
    seatsLeft: 3,
    rating: 4.2,
    reviews: 1200,
    amenities: ['AC', 'WiFi', 'USB Charging'],
    busType: 'AC Seater',
  },
  {
    id: 2,
    name: 'Royal Travels',
    from: 'Delhi',
    to: 'Agra',
    departureTime: '08:00 AM',
    arrivalTime: '12:00 PM',
    duration: '4h',
    price: 550,
    seatsLeft: 8,
    rating: 4.5,
    reviews: 2300,
    amenities: ['AC', 'WiFi', 'USB Charging', 'Water Bottle'],
    busType: 'AC Seater',
  },
  {
    id: 3,
    name: 'Night Express',
    from: 'Delhi',
    to: 'Agra',
    departureTime: '10:00 PM',
    arrivalTime: '03:30 AM',
    duration: '5h 30m',
    price: 650,
    seatsLeft: 12,
    rating: 4.3,
    reviews: 980,
    amenities: ['AC', 'WiFi', 'USB Charging', 'Blanket', 'Water Bottle'],
    busType: 'AC Sleeper',
  },
  {
    id: 4,
    name: 'Speed Line',
    from: 'Delhi',
    to: 'Agra',
    departureTime: '12:00 PM',
    arrivalTime: '04:15 PM',
    duration: '4h 15m',
    price: 420,
    seatsLeft: 5,
    rating: 4.0,
    reviews: 750,
    amenities: ['AC', 'USB Charging'],
    busType: 'AC Seater',
  },
  {
    id: 5,
    name: 'Comfort Plus',
    from: 'Delhi',
    to: 'Agra',
    departureTime: '02:00 PM',
    arrivalTime: '06:45 PM',
    duration: '4h 45m',
    price: 580,
    seatsLeft: 15,
    rating: 4.6,
    reviews: 3200,
    amenities: ['AC', 'WiFi', 'USB Charging', 'Water Bottle', 'Snacks'],
    busType: 'AC Seater',
  },
  {
    id: 6,
    name: 'Budget Travels',
    from: 'Delhi',
    to: 'Agra',
    departureTime: '07:00 AM',
    arrivalTime: '12:00 PM',
    duration: '5h',
    price: 280,
    seatsLeft: 20,
    rating: 3.8,
    reviews: 450,
    amenities: ['Fan', 'Water Bottle'],
    busType: 'Non-AC Seater',
  },
  {
    id: 7,
    name: 'Luxury Coach',
    from: 'Delhi',
    to: 'Agra',
    departureTime: '09:00 AM',
    arrivalTime: '01:00 PM',
    duration: '4h',
    price: 750,
    seatsLeft: 6,
    rating: 4.8,
    reviews: 4100,
    amenities: ['AC', 'WiFi', 'USB Charging', 'Water Bottle', 'Snacks', 'Reading Light'],
    busType: 'Volvo Multi-Axle',
  },
  {
    id: 8,
    name: 'Morning Star',
    from: 'Delhi',
    to: 'Agra',
    departureTime: '05:30 AM',
    arrivalTime: '10:00 AM',
    duration: '4h 30m',
    price: 480,
    seatsLeft: 10,
    rating: 4.4,
    reviews: 1580,
    amenities: ['AC', 'WiFi', 'USB Charging', 'Water Bottle'],
    busType: 'AC Seater',
  },
];

export const cities = [
  'Delhi',
  'Agra',
  'Mumbai',
  'Pune',
  'Bangalore',
  'Chennai',
  'Hyderabad',
  'Kolkata',
  'Jaipur',
  'Ahmedabad',
];
